name=deploii
version=0.1.0
author=Company of Things
maintainer=Company of Things <post@cot.as>
sentence=Library for enabling communication between a MCU and Deploii
paragraph= 
category=Communication
url=https://github.com/Company-of-Things/deploii-library
architectures=esp32
includes=deploii.h
