name=deploii
version=0.3.2
author=Company of Things
maintainer=Company of Things <post@cot.as>
sentence=Library for enabling communication between a MCU and Deploii
paragraph= 
depends=WebSockets, MsgPack, WiFi, WiFiNINA
category=Communication
url=https://github.com/Company-of-Things/deploii-library
architectures=esp32, samd, renesas_uno
includes=deploii.h
