name: CI

on:
  - push
  - pull_request

jobs: 
  build-for-arduino:
    runs-on: ubuntu-latest

      strategy:
        matrix:
          fqbn:
            - arduino:samd:mkrwifi1010

      steps:
        - uses: actions/checkout@v3
        - uses: arduino/compile-sketches@v1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            fqbn: ${{ matrix.fqbn }}
  build-for-esp32:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - 'examples/**'
          cli-compile-flags: |
            - --warnings="none"