name: CI

on:
  - push
  - pull_request

env:
  GLOBAL_LIBS: |
    - source-path: ./
    - name: WiFi
    - name: WebSockets
    - name: Ethernet
    - name: MsgPack

jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: submit
          compliance: strict

  build-for-arduino:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:renesas_uno:unor4wifi

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          libraries: ${{env.GLOBAL_LIBS}}


  build-for-esp32:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          cli-compile-flags: |
            - --warnings="none"
          libraries: ${{env.GLOBAL_LIBS}}